## Python introduction

Python intro:
* Python is high level programming language.
* At the back end of python programming language is connected.

Python Class:
Python
python

# Variable : Fixed memmor location in pyton compiler that will store diff datastructures
# Ruls to create variables:
1. Variable name shuld start with numeric values, it should start with text data
2. If you want to have variable name as a two words you should pass underscore bet the values (machine_learning)
3. Pyton is case sensitive.

#Datatypes in python:
#1. Single value datatype : int,float, boolean
* int : It will store numbers without decimal points, whole numbers(.g. 10,100,550)
* float : It will store nubers with decimal points(e.g. 110.50, 22.20, etc.)
* boolean : It will return o/p as True or False.


#2.Sequential datatype:
*String: " "
*List :[ ]
*Tuple :( )
*Set : {}
*Dictionary :{}

In [1]:
1_one = 5
print(1_one)

<class 'SyntaxError'>: invalid decimal literal (1522140378.py, line 1)

In [2]:
one_1 = 3
print(one_1)

3

In [3]:
x = 100
print(x)

100

In [7]:
Name = "Sakshi"
Age = 12

In [8]:
Name
Age

12

In [12]:
print(Name)
print(type(Name))
print(type(Age))

Sakshi
<class 'str'>
<class 'int'>

# Operators of Python:

* Arithematic Operators
* Comaprison Operators
* Logical Operators

In [13]:
5 + 5

10

In [14]:
a = 10
b = 50
# print (a + b)
c = a + b
print(c)

60

In [15]:
# Division : It will always retirn o/p under float datatype
a = 10
b = 2
c = a/b
print(c)

5.0

In [16]:
# Floor division : It will always return o/p under int datatype
a = 10
b = 2
c = a//2
print(c)

5

In [17]:
# Exponential operator:
2**2

4

In [18]:
2**3

8

In [19]:
5*5

25

In [20]:
# complex number: imaginary numbers
a = 3+2j
print(type(a))

<class 'complex'>

In [21]:
# moduus operator : it will return remainder

a = 25
b = 2
c = a%b
print(c)

1

In [1]:
#Comparison operators: It will always return o/p into boolean datatype
# ==
# >
# <
# >=
# <=
# !=

5>3

True

In [2]:
5 < 2

False

In [3]:
5 == 5

True

In [4]:
5 !=9

True

In [6]:
a =int(input("Enter any value for a: "))
b =int(input("Enter any value for b: "))
c = a + b
print(c)

Enter any value for a:  78
Enter any value for b:  90

168

In [7]:
x = float(input("Enter value for x: "))
y = float(input("Enter any value for y: "))
z = x*y
print(z)

Enter value for x:  10.54
Enter any value for y:  90.7

955.978

In [8]:
Name =(input("Enter value for Name: "))
print(Name)

Enter value for Name:  Prinyanka

Prinyanka

In [9]:
# Python program to find area of rectangle:

length =int(input("Enter len of rect: "))
width =int(input("Enter width of rect:"))
area = length*width
print("Area of rectangle is: ",area)

Enter len of rect:  20
Enter width of rect: 7

Area of rectangle is:  140

In [10]:
# sstobject for boolean :
# Type casing : converting one datatpe into another datatype
boolean_variable = False
print(type(boolean_variable))

<class 'bool'>

In [11]:
a =1,2,3
print(a)

(1, 2, 3)

In [12]:
a =list(range(1,5))
a

[1, 2, 3, 4]

In [13]:
x =10.25
y = int(x)
y

10

In [14]:
# Logica Operators: Logical operators are used to compare or modify the Logic of condiional statements in Python
# In python there are three logical operators:
# AND : if bot the conditions are true then it will print True
# OR : if atleast one of the condition is True then it will print True
# NOT : reverse the result of the conditions

x = 10

print((x >5) & (x < 20))
print((x < 5) | (x > 8))
print(not(x== 10))

True
True
False

In [16]:
boolen_type = True
print(type(boolen_type))

<class 'bool'>

In [18]:
# Type casting : covrting one datatype to another datatype
x = 10
y = float(x)
y

10.0

In [19]:
a = 2.5
b = int(a)
b

2

In [20]:
# String :


string_1 = 'Hello123'
string_1

'Hello123'

In [21]:
# Comparision Operator:
# assignment operator
# > greater than
# < less than
# >= greater than equal to
# <= less than equal to
# == exact match
# != not equalto


print( 5 > 10)
print( 5 == 10)
print(10 < 20)
print(10 != 0)
print( 10 <=8)
print(5 >=5)

False
False
True
True
False
True

In [22]:
string_1 = 'a'
string_2 = "Python is programming language"
string_3 = """Python is the programming language.
            Python is high level , dynamicall type language."""

In [24]:
# Sring datatype : In this datatype you can capture characters/text/numeric into it,
# need to enclose with with("",'',""")
# string is immutable( cannot change or modify)

#single coat example string:
string1 = ' Welcome to ExcelR'
print("Singe coat example : ", string1)

# Double coat exampl
string2 = "This is Python Programming Class"
print("Doule coat example : ",string2)

# Triple Coat example
string3 = """Welcome to Pune"""
print("Triple coat example: ",string3)
print(type(string3))

Singe coat example :   Welcome to ExcelR
Doule coat example :  This is Python Programming Class
Triple coat example:  Welcome to Pune
<class 'str'>

In [1]:
# For string every element has tere position numbers, we cancall it as indexing
# Indexing always starts with 0 it is caled as positive indexing it will start with -1
# Indexing always enclosed with square brackets [].


string ="Welocme to python class"


print("first element: ", string[0])
print("first element: ", string[2])
print("first element: ", string[-1])
print(string[7])
print("Third element: ",string[3])
print("Third last element: ",string[-3])

first element:  W
first element:  l
first element:  s

Third element:  o
Third last element:  a

In [3]:
#slicing [start:stop:step]

string = "Principal Component Analysis"

print(string[20:28])
print(string[0:11])
print(string[1:15])
print(string[1:15:3])
print(string[2:16:2])

print(string[:])
print(string[10:])
print(string[0:9])
print(string[10:19])

Analysis
Principal C
rincipal Compo
rcaCp
icplCmo
Principal Component Analysis
Component Analysis
Principal
Component

In [5]:
# Following are some methods of string datatype:

string = "Principal Component Analysis"

#Upper(): It wil return string into upper case
print(string.upper())

#Lower(): It will return into lowe case
print(string.lower())

#Capitalization(): It will return first letter into capital
print(string.capitalize())

#Find() : It will return position number of element
print(string.find('i'))

#count(): It will return count of element
print(string.count('i'))

#title() : It will return capital letter of every word from string
print(string.title())

#isalpha() : check whethe alphabets are pesent in thestring or not
print(string.isalpha()) # space will not consider under isalpha

PRINCIPAL COMPONENT ANALYSIS
principal component analysis
Principal component analysis
2
3
Principal Component Analysis
False

In [7]:
#isalnum():
string1 = "Text123"
print(string1.isalnum())

True

In [8]:
my_string = "Python Course"
print(len(my_string))

13

In [9]:
#Len : It will count how manyelements are present in given string incusive of spaces.
text ='hello, world'
print(len(text))

12

In [10]:
# isspace() : it ill return true if only spaces are available
print(string1.isspace())

False

In [11]:
my_string_1 = "HelloGoodMorning0123"
print(my_string_1.isspace())

False

In [12]:
string2 = "000 Hello welcome"
print(string2.isspace())

False

In [13]:
string3 = " "
print(string3.isspace())

True

In [14]:
#strip : it will remove leading and trailling spacess:
string3 = "  Principal component Analysis  "
print(string3.strip())

Principal component Analysis

In [16]:
# startswith: it will check exact elemnt at the start from given string
print(string3.startswith("  Pri"))

True

In [18]:
string4 = "Hello Goodmorning"
print(string4.startswith("  He"))
print(string4.endswith("ng"))

False
True

In [20]:
#endswith: it ill check element at the end of given string
print(string3.endswith("sis  "))

True

In [21]:
print(string1.swapcase())

tEXT123

In [5]:
string1 = "WelCome"
print(string1.index("Com"))

3

In [6]:
text = "Hello,World!"
print(len(text))

12

In [7]:
# Type casting :
x = int(10.8)
x

10

In [8]:
y = float(10)
print(y)

10.0

In [9]:
list_1 = []
print(list_1)
print(type(list_1))

[]
<class 'list'>

In [10]:
my_1 = ['Python', 100, 50.25,'True']
my_1

['Python', 100, 50.25, 'True']

In [12]:
student_info = [["Priya", 22,95],
                ["Sahil",24,98.77],
                ["raj", 25, 88]]
student_info

[['Priya', 22, 95], ['Sahil', 24, 98.77], ['raj', 25, 88]]

In [13]:
#List : A listis a built in data structure in python used to store multiple valuesin single variable.
# It will act as storage cantainer we can create list in squar bracket

# List features:
# 1. ordered(values from list have index positions)
# 2. mutable(can be changed)
# 3. it allow duplication values

# empty list :
empty_lst = []
print(empty_lst)
print(type(empty_lst))

[]
<class 'list'>

In [14]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [15]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [16]:
my_list = [10,20,"Python Courde",200.55,90]
print(my_list)
print(type(my_list))

[10, 20, 'Python Courde', 200.55, 90]
<class 'list'>

In [17]:
int_val = [10,20,30,40,50]
print(int_val)

[10, 20, 30, 40, 50]

In [22]:
# List methods:
# append(): it will adds an element at the end of the list

numbers = [1,2,3,4]
numbers.append(5)
print(numbers)

[1, 2, 3, 4, 5]

In [25]:
num = [10,20,30,40,50]
num.append(60)
print(num)

num1 = [70,80,90]
num.extend(num1)
print(num)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [26]:
# extend () : It will extend from another list

a = [1,2]
b = [3,4]
a.extend(b)
print(a)

[1, 2, 3, 4]

In [27]:
# insert() : insert an element at a specific index
nums = [10,20,30]
nums.insert(1,15)
print(nums)

[10, 15, 20, 30]

In [28]:
# remove() : it will removes the first occurence of specific values

nums = [10,20,10,"abc",30,40,10]
nums.remove(10)
print(nums)

[20, 10, 'abc', 30, 40, 10]

In [30]:
# pop(): removes and returns an element (default last element will be remove)

data = [10,20,"Python",30,40.55,50]
data.pop()
print(data)

[10, 20, 'Python', 30, 40.55]

In [31]:
data.pop(1)

20

In [33]:
# clear (): it will return empty list

lst_1 = [50,60,70,'abc','20/7/2026']
lst_1.clear()
print(lst_1)

[]

In [34]:
text = "python"
new_text = "".join(sorted(text, reverse = True))
print(new_text)

ytponh

In [37]:
text = "PYTHON"
new_text =(sorted(text))
print(new_text)

['H', 'N', 'O', 'P', 'T', 'Y']

In [39]:
my_list_1 = [5.5,7.5,8.9,10,5,4,65]
print(len(my_list_1))
print(min(my_list_1))
print(max(my_list_1))

7
4
65

In [40]:
# index () : it wil return the index of first occurences of a value

nums = [10,20,30,40,50,60,70]
print(nums.index(60))

5

In [41]:
# count() : counts how many times value appears in datastructure

list_1 = [10,50,"WEB",89,100,100,50]
print(list_1.count(100))

2

In [42]:
# sort() : sorts the data in as ending order(by default)

nums = [3,1,2,4,9,5,8,10]
nums.sort()
print(nums)

[1, 2, 3, 4, 5, 8, 9, 10]

In [43]:
# sort (): sorts the data in ascnding order(by default)

nums = [3,1,2,4,9,5,8,10]
nums.sort(reverse=True)
print(nums)

[10, 9, 8, 5, 4, 3, 2, 1]

In [44]:
# copy() : create a shallow copy of the list

a = [1,2,3]
b = a.copy()
print(b)

[1, 2, 3]

In [45]:
# len() : it will return how man elements are there in data structure

my_list = [10,20,"Python",100.50,200]
len(my_list)

5

In [46]:
my_list = [10,20,30,40,50,60,70,500]
print(min(my_list))

10

In [47]:
my_list = [10,20,30,40,50,60,70,500]
print(max(my_list))

500

In [48]:
# List slicing 

nums = [10,20,30,40,50,60,70,80]
print(nums[1:3])
print(nums[2:])
print(nums[::2])
print(nums[::-1])
print(nums[3:7])
(nums[4])

[20, 30]
[30, 40, 50, 60, 70, 80]
[10, 30, 50, 70]
[80, 70, 60, 50, 40, 30, 20, 10]
[40, 50, 60, 70]
50

In [50]:
new_nums = nums[:]
print(new_nums)

[10, 20, 30, 40, 50, 60, 70, 80]

In [52]:
# nested list and nested indxing , silicing :nested list is nothing but list inside list,
# and ftching out values from such datatype is nested indexing and slicing

nested_list = [["Python","Java","C++"],
               ["SQL","MangoDB","Oracle"],
               ["AI","GenAI","Deep Learning"]]

nested_list
print(nested_list[0][0:2])
print(nested_list[2][2])

['Python', 'Java']
Deep Learning

In [53]:
# List comprehension : is a short and elegant way to write and create a new list from
# an existing element to new iterable
# new_list = [expession for item in iterable]

numbers = [1,2,3,4,5]
square = []

for num in numbers:
    square.append(num**2)
print(square)

[1, 4, 9, 16, 25]

In [54]:
square = [x**2 for x in range (1,6)]
print(square)

[1, 4, 9, 16, 25]

In [56]:
# Even numbers with list comprehension:
even = [x for x in range(1,11) if  x % 2 ==0]
print(even)

[2, 4, 6, 8, 10]

In [45]:
# Nested List: nested list and nested indexing slicing

info = [["Laptop",65000,["Dell","i5"],True],
        ["Mobile",30000,["Samsung","android"],False]]
print(info)

[['Laptop', 65000, ['Dell', 'i5'], True], ['Mobile', 30000, ['Samsung', 'android'], False]]

In [46]:
print(info[0][2][0])

Dell

In [47]:
print(info[1][2][:])

['Samsung', 'android']

In [48]:
# Tuple : A tuple is a built in data structure used to store multiple values in a single variable
# simimlar to a list but is immutable(cannot be changed after creation)
# we can declare tuples with round brackets()


#Real world exampe for tuple:
# 1. DOB
# 2. Aadhar card, PAN

#Characteritics of tuple:
# 1. Ordered sequence (index based)
# 2. Immutable
# 3. Allow duplicate values
# 4. can store mixed data tupes

In [49]:
t1 = ()
print(type(t1))

<class 'tuple'>

In [50]:
t = (10,"Rutuja","WEB",20,200.55)
print(t)
print(type(t))

(10, 'Rutuja', 'WEB', 20, 200.55)
<class 'tuple'>

In [51]:
tuple_1 = (10,20,30,40)
print(tuple_1)
print(type(tuple_1))

(10, 20, 30, 40)
<class 'tuple'>

In [52]:
t2 = (20,)
print(type(t2))

<class 'tuple'>

In [54]:
# Tuple with single element:

t = (10,)
print(t)
print(type(t))

(10,)
<class 'tuple'>

In [55]:
# Single element tuple without comma:

t = (10)
print(type(t))

<class 'int'>

In [57]:
# ACcesing of tuple elements (Indexing):

color = ("red","Green","Yellow","White")
print(color[1])
print(color[-1])
print(color[1:3])

Green
White
('Green', 'Yellow')

In [58]:
# Tuple slicing:

nums = (10,20,30,40,50)
print(nums[1:4])
print(nums[:3])
print(nums[::-1])

(20, 30, 40)
(10, 20, 30)
(50, 40, 30, 20, 10)

In [59]:
# Tuple with mixed datatype:

info = (101,"Anita",85.5, True)
print(info)

(101, 'Anita', 85.5, True)

In [60]:
info = (("Rahul","Raj","Nidhi"),
        ("SQL","Python","AI"))

print(info)
print(info[0][1])
print(info[1][2])

(('Rahul', 'Raj', 'Nidhi'), ('SQL', 'Python', 'AI'))
Raj
AI

In [63]:
# Nested tuple with nested indexing example:

data = (
    (1,"math",90),
    (2,"science",89)
)
print(data[1][1])

science

In [64]:
# Methods of tuples:
# Count() : count number of elements

t = (1,2,2,3,3,3,4,5,4,7,4)
print(t.count(4))

3

In [65]:
# Index:

print(t.index(3))

3

In [66]:
fruits = ("Apple","Kiwi","Melon")

red, brown, green = fruits

print(red)
print(brown)

Apple
Kiwi

In [67]:
# Tuple packing and unpacking:

student = ("Rahul",22,"CSE") # packing of tuple

# Unpacking of tuple:

name , age, branch = student
print(name)
print(age)
print(branch)

Rahul
22
CSE

In [69]:
# Item assignment in tuple:

t = (1,2,3,4,5)
t[0] = 1.2
print(t)  # error because tuple is immutable

<class 'TypeError'>: 'tuple' object does not support item assignment

In [71]:
list_1 = [10,20,30,40,50]
list_1[0] = 10.5
print(list_1)

[10.5, 20, 30, 40, 50]

## DICTIONARY

In [73]:
# Dictionary : In python dictionary is buil in data structure used to store data in
# key value pairs. Can be created with curly brackets{}

# Characteristics of dictionary:
# 1. stores data as key:value pair
# 2. unordered
# 3. Mutable

In [74]:
# Create dictinary:

students = {
    "id":101,
    "name":"Amit",
    "marks":88.9,
    "Result":True,
}
print(students)

{'id': 101, 'name': 'Amit', 'marks': 88.9, 'Result': True}

In [75]:
print(students["name"])

Amit

In [76]:
print(students["marks"])

88.9

In [77]:
# get() : to get access elements from dictionary
print(students.get("marks"))

88.9

In [79]:
# Adding & updating:

students["grade"] = "A"  # add
students["marks"] = 98
students["result"] = "Pass" # update value

In [80]:
students

{'id': 101,
 'name': 'Amit',
 'marks': 98,
 'Result': True,
 'grade': 'A',
 'result': 'Pass'}

In [81]:
data = {
    "name": "priya",
    "age": 28
}

print(data)


print(data.get("name"))
print(data.get("city"))
print(data.get("city","Not found"))

{'name': 'priya', 'age': 28}
priya
None
Not found

In [82]:
print(data.keys())

dict_keys(['name', 'age'])

In [83]:
print(data.values())

dict_values(['priya', 28])

In [84]:
print(data.items())

dict_items([('name', 'priya'), ('age', 28)])

In [85]:
data.update({"city": "Pune","subject":"Python"})
print(data)

{'name': 'priya', 'age': 28, 'city': 'Pune', 'subject': 'Python'}

In [86]:
data.clear()
print(data)

{}

In [87]:
print(data.setdefault("city","pune"))
data

pune

{'city': 'pune'}

In [88]:
student ={
    "name" : ["Raj","Amit","Sumit","Priya"],
    "age" : [22,30,23,25],
    "course" : ["DS","AI","DA","BA"]
}

student

{'name': ['Raj', 'Amit', 'Sumit', 'Priya'],
 'age': [22, 30, 23, 25],
 'course': ['DS', 'AI', 'DA', 'BA']}

In [89]:
for key in student:
    print(key)

name
age
course

In [90]:
for value in student.values():
    print(value)

['Raj', 'Amit', 'Sumit', 'Priya']
[22, 30, 23, 25]
['DS', 'AI', 'DA', 'BA']

In [91]:
for key,value in student.items():
    print(key,":",value)

name : ['Raj', 'Amit', 'Sumit', 'Priya']
age : [22, 30, 23, 25]
course : ['DS', 'AI', 'DA', 'BA']

In [92]:
# Removing an element

students.pop("result")

'Pass'

In [93]:
# NEsted dictionary :

employees = {
    "emp1":{"name":"Amit","Salary":50000,"Design":"HR"},
    "emp2":{"name":"Neha","Salary":60000,"Design":"Manager"},
    "emp3":{"name":"Mansi","Salary":65000,"Design":"Prof"},
}
employees

{'emp1': {'name': 'Amit', 'Salary': 50000, 'Design': 'HR'},
 'emp2': {'name': 'Neha', 'Salary': 60000, 'Design': 'Manager'},
 'emp3': {'name': 'Mansi', 'Salary': 65000, 'Design': 'Prof'}}

# Real world dictionary:
1. To store emp record
2. To store student record
3. Confuguration record
4. Product prices

# Set
* A set is a built in structure used to store unique elements in single variable
* Unordered collection (no index position)
* It is mutable datastructure

In [95]:
numbers = [1,2,3,4]
print(numbers)

[1, 2, 3, 4]

In [96]:
set_1 ={10,20,30,10,20,10,10,40,50,10}
print(set_1)

{50, 20, 40, 10, 30}

In [97]:
# Empty set:
s = {}
print(s)
print(type(s))

{}
<class 'dict'>

In [99]:
s = set()
print(type(s))

<class 'set'>

In [100]:
# Set methods:
# add() : adds one element to the set

s = {1,2,3}
s.add(4)
print(s)

{1, 2, 3, 4}

In [102]:
# Update : Adds multuple elements at the end of set
set_1 = {1,2,3,4}
set_1.update([5,6,7])
set_1

{1, 2, 3, 4, 5, 6, 7}

In [106]:
# remove () : remove specific element from set
set_1.remove(2)
set_1

{1, 3, 4, 5, 6, 7}

In [107]:
set_1.discard(5)
set_1

{1, 3, 4, 6, 7}

In [108]:
fruits = {"apple","kiwi"}
fruits.add('melon')
print(fruits)

{'melon', 'kiwi', 'apple'}

In [110]:
# To update to add multiple elements
fruits.update(["mango","orange"])
print(fruits)

{'mango', 'melon', 'orange', 'kiwi', 'apple'}

In [3]:
from functools import reduce

number = [1,2,3,4]

total = reduce(lambda a,b : a+b,number)
print(total)

10

In [4]:
from functools import reduce

numbers =[12,45,8,99,23,32]

largest = reduce(lambda x,y : x if x > y else y,numbers)
print(largest)

99

In [5]:
words = ["Pyhon","AI","MachineLearning","SQL"]

largest = reduce(lambda x,y : x if len(x) > len(y) else y, words)
print(largest)

MachineLearning

In [9]:
!pip install numpy

mambajs 0.21.4

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.

In [10]:
# numpy is the lbrabry used for fast numerical operation
#You can create n dimension array(ndarray) and perform mathematical operations
#!pip install <Librabry  name>
# faster than python list to stoe multidiemnsional array
import numpy

In [12]:
import numpy as np

In [13]:
arr = np.array([10,20,30,40])

print(arr)

[10 20 30 40]

In [19]:
# array with rows

arr = np.array([[1,2,3],
              [4,5,6]])

print(arr)
print(arr.ndim) # numbers of dimensions
print(arr.shape)  # numbers of rows and number of columns
print(arr.size)  #total elements
print(arr.dtype) # it will return datatype

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32

In [23]:
# Special array:

np.zeros((2,3))
np.ones((2,2))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# arange 
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]

In [25]:
num = np.arange(2,21,2)
print(num)

[ 2  4  6  8 10 12 14 16 18 20]

In [26]:
#Linespace() : create evenly spaced numbers

num_2 = np.linspace(0,10,5)
print(num_2)

[ 0.   2.5  5.   7.5 10. ]

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
data = np.array([[24,170,84,100],[28,168,80,120],[32,171,75,105],[34,170,78,108],[32,173,65,110]])
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 32, 173,  65, 110]])

In [34]:
data[:,3:4]

array([[100],
       [120],
       [105],
       [108],
       [110]])

In [36]:
data[:2:2]

array([[ 24, 170,  84, 100]])

In [37]:
# we ca fetch the elements from numpy array with the help of silicing
data[:,2:3]

array([[84],
       [80],
       [75],
       [78],
       [65]])

In [40]:
data[:,0:2]

array([[ 24, 170],
       [ 28, 168],
       [ 32, 171],
       [ 34, 170],
       [ 32, 173]])

In [42]:
data[0:2,0:1]

array([[24],
       [28]])

In [43]:
#performing math computation on sepcific column

print("Mean: ",np.mean(data[:,0:1]))

Mean:  30.0

In [45]:
print("Median: ",np.median(data[:,0:1]))

Median:  32.0

In [5]:
import numpy as np
# rabdom(): to generate random numbers using numpy

a1 = np.random.randint(10,50, size=4)
a1

array([48, 14, 13, 41])

In [6]:
np.random.rand()

0.9399850329178725

In [7]:
np.random.rand(5)

array([0.09308202, 0.5560668 , 0.54811359, 0.09007466, 0.50167968])

In [8]:
#creating the data in 1D

x1 = np.random.randint(30,70, size =4)
x1

array([33, 57, 36, 63])

In [9]:
x1.ndim

1

In [10]:
#2D array

x2 = np.random.randint(10,40, size=(3,4))
x2

array([[23, 26, 33, 27],
       [21, 22, 14, 23],
       [34, 11, 11, 17]])

In [11]:
x2.ndim

2

In [14]:
x3 = np.random.randint(10,50,size=(3,4,3))  #(size(repetition,row,col))
x3

array([[[10, 18, 18],
        [17, 41, 36],
        [20, 15, 39],
        [27, 45, 28]],

       [[32, 38, 32],
        [12, 40, 31],
        [35, 10, 43],
        [18, 25, 32]],

       [[44, 42, 44],
        [41, 28, 22],
        [34, 35, 29],
        [18, 23, 48]]])

In [18]:
x3.ndim

3

In [19]:
x3.size

36

In [20]:
x3.shape

(3, 4, 3)

In [15]:
#np.random.choice(): randoml select values from an array

arr = np.array([10,20,30,40,50])
np.random.choice(arr)

np.int32(40)

In [16]:
np.random.choice(arr,3)

array([50, 30, 30])

In [17]:
#np.random.seed() : used when you want soe random numbers every time

np.random.seed(42)

print(np.random.randint(2,4))

2

In [23]:
data = np.array([[24,170,84,100],[23,56,78,90],[32,189,98,123],[34,89,56,145],[32,78,96,178]])
data

array([[ 24, 170,  84, 100],
       [ 23,  56,  78,  90],
       [ 32, 189,  98, 123],
       [ 34,  89,  56, 145],
       [ 32,  78,  96, 178]])

In [ ]:
!pip install pandas

mambajs 0.21.4

Process pip requirements ...

Cannot install 'pandas' from PyPI because it is a binary built package that is not compatible with WASM environments. To resolve this issue, you can: 1) Try to install it from emscripten-forge instead: "!mamba install pandas" 2) If that doesn't work, it's probably that the package was not made WASM-compatible on emscripten-forge. You can either request or contribute a new recipe for that package in https://github.com/emscripten-forge/recipes

In [1]:
!mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 7.290 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [11]:
import numpy as np

In [12]:
data = np.array([[24,170,89,78],[56,23,45,67],[90,89,78,45],[23,56,78,900],[78,67,48,89]])
data

array([[ 24, 170,  89,  78],
       [ 56,  23,  45,  67],
       [ 90,  89,  78,  45],
       [ 23,  56,  78, 900],
       [ 78,  67,  48,  89]])

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame(data)
df

    0    1   2    3
0  24  170  89   78
1  56   23  45   67
2  90   89  78   45
3  23   56  78  900
4  78   67  48   89

In [15]:
df.column =["Age","Height","Weight","BP"]
df

/tmp/xpython_42/1109131543.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.column =["Age","Height","Weight","BP"]

    0    1   2    3
0  24  170  89   78
1  56   23  45   67
2  90   89  78   45
3  23   56  78  900
4  78   67  48   89

In [16]:
df.index = ['a','b','c','d','e']
df

    0    1   2    3
a  24  170  89   78
b  56   23  45   67
c  90   89  78   45
d  23   56  78  900
e  78   67  48   89

In [18]:
data_3 =[['Priya',30,'Pune'],
         ['Rahul',25,'Mumbai'],
         ['Sneha',28,'Banglore']]

series = pd.DataFrame(data_3 , columns=['Name','Age','City'])
series

    Name  Age      City
0  Priya   30      Pune
1  Rahul   25    Mumbai
2  Sneha   28  Banglore

In [19]:
import numpy as np

array_1 = np.array([[1,2,3],[4,5,6]])
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(array_1.shape) #return no of rows and columns
print(array_1.size)  # no. of elements in array
print(array_1.dtype) # it will return datatype in array
print(array_1.ndim)  # it will return dimension in array

(2, 3)
6
int32
2

In [22]:
array_2 =array_1.astype('float')
array_2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
np.log10(100)

np.float64(2.0)

In [24]:
np.log(10)

np.float64(2.302585092994046)

In [25]:
np.log(1)

np.float64(0.0)

In [26]:
np.tanh(45)

np.float64(1.0)

In [27]:
np.sin(array_1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [28]:
np.nan  # used to represent missing or unaviable data

nan

In [29]:
np.array([np.nan,12,34])

array([nan, 12., 34.])

In [30]:
np.sqrt(9)

np.float64(3.0)

In [31]:
np.absolute(-90)

np.int32(90)

In [32]:
np.round(45.8905678)

np.float64(46.0)

# PANDAS LIBRABRY

In [34]:
import pandas as pd

In [36]:
df = pd.read_csv("nyc_weather (1).csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109
10,01-11-2016,33,8,37,29.92,10,7,0,1,NaN,289
11,01-12-2016,35,15,53,29.85,10,6,T,4,NaN,235
12,01-13-2016,26,4,42,29.94,10,10,0,0,NaN,284
13,01-14-2016,30,12,47,29.95,10,5,T,7,NaN,266
14,01-15-2016,43,31,62,29.82,9,5,T,2,NaN,101
15,01-16-2016,47,37,70,29.52,8,7,0.24,7,Rain,340
16,01-17-2016,36,23,66,29.78,8,6,0.05,6,Fog-Snow,345
17,01-18-2016,25,6,53,29.83,9,12,T,2,Snow,293
18,01-19-2016,22,3,42,30.03,10,11,0,1,NaN,293
19,01-20-2016,32,15,49,30.13,10,6,0,2,NaN,302
20,01-21-2016,31,11,45,30.15,10,6,0,1,NaN,312
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EST                   31 non-null     str
 1   Temperature           31 non-null     int64
 2   DewPoint              31 non-null     int64
 3   Humidity              31 non-null     int64
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64
 6   WindSpeedMPH          31 non-null     int64
 7   PrecipitationIn       31 non-null     str
 8   CloudCover            31 non-null     int64
 9   Events                9 non-null      str
 10  WindDirDegrees        31 non-null     int64
dtypes: float64(1), int64(7), str(3)
memory usage: 2.4 KB

In [38]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333

In [39]:
df.head(25)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109
10,01-11-2016,33,8,37,29.92,10,7,0,1,NaN,289
11,01-12-2016,35,15,53,29.85,10,6,T,4,NaN,235
12,01-13-2016,26,4,42,29.94,10,10,0,0,NaN,284
13,01-14-2016,30,12,47,29.95,10,5,T,7,NaN,266
14,01-15-2016,43,31,62,29.82,9,5,T,2,NaN,101
15,01-16-2016,47,37,70,29.52,8,7,0.24,7,Rain,340
16,01-17-2016,36,23,66,29.78,8,6,0.05,6,Fog-Snow,345
17,01-18-2016,25,6,53,29.83,9,12,T,2,Snow,293
18,01-19-2016,22,3,42,30.03,10,11,0,1,NaN,293
19,01-20-2016,32,15,49,30.13,10,6,0,2,NaN,302
20,01-21-2016,31,11,45,30.15,10,6,0,1,NaN,312
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286

In [40]:
df.tail()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [41]:
df.tail(10)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [42]:
df.describe() # return all mathematical computation of eac varaible

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.903226,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.724639,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,7.000000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [43]:
df["Temperature"].describe()

count    31.000000
mean     34.677419
std       7.639315
min      20.000000
25%      29.000000
50%      35.000000
75%      39.500000
max      50.000000
Name: Temperature, dtype: float64